# Generated by Django 5.0.2 on 2024-03-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='descripcion',
        ),
    ]
